# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 25

[font.normal]
family = "UbuntuMono Nerd Font"
# family = "CaskaydiaCove Nerd Font"
# family = "CaskaydiaMono Nerd Font"
# family = "FiraMono Nerd Font"
# family = "IosevkaTerm Nerd Font Mono"
# family = "JetBrainsMono Nerd Font"
# family = "Hack Nerd Font Mono"

[window]
decorations = "Full"
position = { x = 10, y = 10 } # (has no effect on Wayland)
dimensions = { columns = 120, lines = 80 }
# opacity = 1.0
# blur = true

[window.padding]
x = 7
y = 0

[shell]
#MAC
program = "/opt/homebrew/bin/tmux"
#LINUX
# program = "/usr/bin/tmux"
args = ["new", "-A", "-D", "-s", "main"]


#option_as_alt = "Both"

[terminal]
shell = { program = "/opt/homebrew/bin/bash/", args = ["-l"] }
